### ISSUE TITLE
Data Retrieval not retrieving NDs

### ISSUE THREAD

**Issue by jmacart** [USGS-R/EGRET#100]
Data Retrieval is not retrieving NDs for any MN data stored after 2002 or so.  I get the concentration reports as 0 message although the concentration was not reported as 0 and our statewide data retrieval has no problem getting it.  Following is the sample retrieval code:  

siteNumber <- "MNPCA-S002-010"
> characteristicName <- "Inorganic nitrogen (nitrate and nitrite)"
> startDate <- "1992-01-01"
> endDate <- "2015-12-31"
> Sample <- readWQPSample(siteNumber, characteristicName, startDate,endDate)
Deleted Rows:
      dateTime ConcLow ConcHigh Uncen
4   2010-09-20       0        0     1
5   2010-10-20       0        0     1
8   2010-10-12       0        0     1
11  2010-07-13       0        0     1
13  2010-07-27       0        0     1
15  2010-04-21       0        0     1
17  2010-08-09       0        0     1
18  2010-05-19       0        0     1
19  2010-07-07       0        0     1
20  2011-11-01       0        0     1
22  2011-09-13       0        0     1
23  2011-11-16       0        0     1
25  2011-06-15       0        0     1
27  2011-05-18       0        0     1
33  2011-05-09       0        0     1
36  2011-06-08       0        0     1
45  2013-10-09       0        0     1
51  2013-08-06       0        0     1
53  2013-05-29       0        0     1
54  2013-08-27       0        0     1
58  2005-08-17       0        0     1
59  2010-12-06       0        0     1
60  2010-01-12       0        0     1
63  2010-08-23       0        0     1
64  2010-11-22       0        0     1
65  2010-06-08       0        0     1
67  2010-05-13       0        0     1
68  2010-05-26       0        0     1
69  2010-10-05       0        0     1
74  2004-10-20       0        0     1
84  2008-10-07       0        0     1
87  2008-09-09       0        0     1
88  2008-07-09       0        0     1
90  2008-11-04       0        0     1
92  2008-12-09       0        0     1
96  2007-05-14       0        0     1
97  2009-05-13       0        0     1
98  2009-04-22       0        0     1
101 2009-07-29       0        0     1
102 2009-09-15       0        0     1
105 2009-05-20       0        0     1
107 2009-08-11       0        0     1
109 2009-06-23       0        0     1
110 2009-08-26       0        0     1
111 2009-04-29       0        0     1
112 2009-07-14       0        0     1
113 2009-05-06       0        0     1
114 2009-12-01       0        0     1
115 2009-06-09       0        0     1
120 2013-06-17       0        0     1
123 2013-09-10       0        0     1
125 2013-09-25       0        0     1
128 2005-04-20       0        0     1
131 2005-08-31       0        0     1
132 2005-05-18       0        0     1
134 2005-11-02       0        0     1
136 2005-05-11       0        0     1
137 2005-09-14       0        0     1
138 2005-05-23       0        0     1
140 2005-08-03       0        0     1
141 2005-04-27       0        0     1
143 2005-05-04       0        0     1
149 2012-10-17       0        0     1
151 2012-06-25       0        0     1
152 2012-07-02       0        0     1
153 2012-04-10       0        0     1
154 2012-05-14       0        0     1
155 2012-06-05       0        0     1
162 2012-04-30       0        0     1
165 2012-05-22       0        0     1
167 2012-09-11       0        0     1
168 2012-11-07       0        0     1
170 2007-07-17       0        0     1
172 2007-05-21       0        0     1
173 2007-06-26       0        0     1
174 2007-08-27       0        0     1
184 2007-09-17       0        0     1
195 2015-05-11       0        0     1
198 2015-04-28       0        0     1
200 2015-10-27       0        0     1
201 2015-08-03       0        0     1
202 2015-04-13       0        0     1
204 2015-06-23       0        0     1
205 2015-09-22       0        0     1
207 2015-08-25       0        0     1
215 2015-11-04       0        0     1
258 2006-06-21       0        0     1
259 2006-09-27       0        0     1
260 2006-07-17       0        0     1
262 2006-08-23       0        0     1
264 2006-09-05       0        0     1
265 2006-06-07       0        0     1
266 2006-04-19       0        0     1
267 2006-05-10       0        0     1
270 2006-08-02       0        0     1
272 2009-10-07       0        0     1
275 2014-10-28       0        0     1
283 2014-05-27       0        0     1
284 2014-09-30       0        0     1
285 2014-09-08       0        0     1
289 2014-11-25       0        0     1
Warning message:
In compressData(data, interactive = interactive) :
  Deleted 101 rows of data because concentration was reported as 0.0, the program is unable to interpret that result and is therefore deleting it.
> 
  Thank You

**Comment by ldecicco-USGS** [comment]
Sorry for the delayed response. Can you update your packages and try again? I get censored values for the same workflow:
```
library(EGRET)
siteNumber <- "MNPCA-S002-010"
characteristicName <- "Inorganic nitrogen (nitrate and nitrite)"
startDate <- "1992-01-01"
endDate <- "2015-12-31"
Sample <- readWQPSample(siteNumber, characteristicName, startDate,endDate)
```
There were some updates to `dataRetrieval` awhile back that may have fixed this. If you update and still are getting 0's instead of censored values, can you paste the results of `sessionInfo()`. 

Thanks!

![update](https://user-images.githubusercontent.com/1105215/26993188-9be2be92-4d27-11e7-920f-12df2e0aaad6.png)

**Comment by jmacart** [comment]
Thank you Laura.  I tried it on one of my ND sites and it seems to work now.  I will let you know if I run into any other problems.  Lots of ND’s for nitrogen up in the north.

JM
