### ISSUE TITLE
package or namespace load failed for ‘EGRET’

### ISSUE THREAD

**Issue by tungmilan** [USGS-R/EGRET#101]
I'm having the following issue when loading EGRET. Something wrong related to dplyr?

```
> library(EGRET)
Error: package or namespace load failed for ‘EGRET’:
 object ‘rbind_all’ is not exported by 'namespace:dplyr'

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-05-08                  

Packages ---------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                           
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                   
 curl         2.6        2017-04-27 CRAN (R 3.4.0)                   
 devtools     1.12.0     2016-12-05 CRAN (R 3.4.0)                   
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                   
 dplyr        0.5.0.9004 2017-05-01 Github (hadley/dplyr@106070a)    
 glue         1.0.0      2017-05-01 Github (tidyverse/glue@650d0d3)  
 lubridate    1.6.0      2016-09-13 CRAN (R 3.3.1)                   
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                   
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                   
 R6           2.2.0      2016-10-05 CRAN (R 3.4.0)                   
 Rcpp         0.12.10.2  2017-05-01 Github (RcppCore/Rcpp@c57b754)   
 rlang        0.0.0.9018 2017-05-01 Github (hadley/rlang@b22ce1c)    
 stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                   
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                   
 tibble       1.3.0.9001 2017-04-24 Github (tidyverse/tibble@08af6b0)
 withr        1.0.2      2016-06-20 CRAN (R 3.4.0) 
```

Thanks!

Tung

**Comment by jiwalker-usgs** [comment]
It looks to me like the `rbind_all()` function has been deprecated in latest version of dplyr.  EGRET will need to be updated to remove calls to this function.

**Comment by ldecicco-USGS** [comment]
I'm looking into it, but I can't seem to find any use of `rbind_all` in `EGRET`.... 

There will be an update available on CRAN shortly for `dataRetrieval`, but using `rbind_all` doesn't fit in there either. 

How were you installing `EGRET`?

**Comment by tungmilan** [comment]
Thanks! I just installed EGRET from CRAN. Maybe the problem was due to I'm using the developed version of dplyr?

**Comment by ldecicco-USGS** [comment]
Can you paste your output when you try to install `EGRET`, because there is no direct dependency of `dplyr` on `EGRET`. (there is indirectly with `dataRetrieval`...but again....neither `EGRET` or `dataRetrieval` use `rbind_all`...I'm just trying to figure out how you are installing it.

Perhaps it's the CRAN repository that you are using? I'd recommend RStudio's "cloud" service. 

So, what do you get when you type:

```
install.packages("EGRET", repos = "https://cloud.r-project.org")
```

**Comment by tungmilan** [comment]
I'm running into problem when using `install.packages` for R 3.4.0 on Windows 10

`Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  :`
`missing value where TRUE/FALSE needed`

After installing `R-patched` version, `dply`r from CRAN, `EGRET` works again
https://cran.r-project.org/bin/windows/base/rpatched.html

Thanks!

**Comment by ldecicco-USGS** [comment]
Yeah, the `file.exists` error is a window's bug in R. Glad to hear it's working now.
