### ISSUE TITLE
Add tests to modeling functions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#102]
- [x] modelEstimation
- [x] estCrossVal
- [x] estSurfaces
- [x] runSurvReg
- [x] estDailyFromSurfaces

Upon adding tests with the Choptank and/or Arkansas sample data, look for places to add intermediate functions.

**Comment by lindsaycarr** [comment]
Going to let @ldecicco-USGS review the tests before closing this issue!
