### ISSUE TITLE
Add tests to table output and other functions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#103]
- [x] calculateMonthlyResults
- [x] censoredSegments 
- [x] checkStartEndDate 
- [x] compressData 
- [x] dateFormatCheck 
- [x] flowDuration
- [x] formatCheckDate
- [x] formatCheckParameterCd 
- [x] logPretty1
- [x] logPretty3
- [x] makeAnnualSeries
- [x] makeAugmentedSample   this doesn't have an example either
- [x] setSeasonLabel
- [x] mergeReport
- [x] populateConcentrations   better documentation - what actually are the columns?
- [x] selectDays
- [x] setPA
- [x] generalAxis 
- [x] fluxBiasStat

Upon adding tests with the Choptank and/or Arkansas sample data, look for places to add intermediate functions. I expect fewer intermediate functions needed here than #102

**Comment by wdwatkins** [comment]
#125 covered this
