### ISSUE TITLE
Add flexible flow normalization to setupYears

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#121]
OK... here it goes. We already have a function `flexFN` that let's you permanently set the flow-normalized calculations to some set of years. This issue is both a simplification of that function, and only temporary. It can either be called within `setupYears`, or before. It would probably be easiest to implement by putting it within `setupYears`, and setting a default argument to use the full period of record.

The function `flexFN` takes a data frame with 3 columns, the first represents where to split the surface, the second and 3rd where to split the discharge. 

Instead of that workflow, I'd say we'll only concentrate on discharge, with a single vector of dates to normalize on. 

 - [x] Add more tests to `setupYears`
 - [x] Improve documentation to `estFNsegs`
 - [x] Create function to use vector of years. 
 - [x] Add it to functions before `setupYears`
 - [ ] Double-check all the output for those functions that call `setupYears` (many are graphing functions)
 - [ ] Add examples to functions that call `setupYears`
 - [ ] Write mini-vignette/blog.

@lindsaycarr I'm going to do a couple of these first tasks this afternoon to get it started. I'll have you review whatever PR I end up completing and then you take over from there.

**Comment by ldecicco-USGS** [comment]
Upon further reflection, I think `estFNsegs` should be an internal function, so can hang tight on improving the documentation for now

**Comment by lindsaycarr** [comment]
@ldecicco-USGS is this just for plotting functions?
