### ISSUE TITLE
Allow for right-censored data

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/EGRET#137]
Currently, only `<` is recognized as a censored value, and when `>` appears in the QW data, the value is documented as uncensored and ConcLow and ConcHigh are equal. Per `survival` package documentation, ConcLow should be the censored value, and ConcHigh should be `NA`. 

This requires changes to `populateConcentrations` and `populateSampleColumns`.

**Comment by rmhirsch49** [comment]
I've never encountered a > in the NWIS data set.  Can you provide more information about it.  I'm curious about what the parameter code was and what the value was.  Is there anything in NWIS documentation about > values?  Could this be something new that is a result of the recent re-design of NWIS?

**Comment by limnoliver** [comment]
Right censored data are appearing in our fecal coliform and BOD parameters. It's not an issue related to NWIS as these are data coming from collaborators in Milwaukee (MMSD), though I'm guessing there are right censored values for those parameters in NWIS.

**Comment by ldecicco-USGS** [comment]
Plotting-wise, and data-input-wise, I think we're good. I'd say the last step would be to write some tests to verify the WRTDS model is doing things that make sense.
