### ISSUE TITLE
Y-axis of plotContours: is possible not to plot in log transformed flow?

### ISSUE THREAD

**Issue by ghost** [USGS-R/EGRET#142]
Thanks for reading this.  I noticed that the function of plotContours will automatically plot y-axis as log-transformed stream discharge.  Is there a way to plot the discharge without log-transforming data? 

Thank you.
Wenlong

**Comment by ldecicco-USGS** [comment]
There's not an easy way to do that. For now, you could make your own plotContours_linear by copying this:

https://github.com/USGS-R/EGRET/blob/master/R/plotContours.R

And fiddle with the log functions is the call to filled.contour and the following axis calls. I'll think about if it makes sense to add that enhancement to the next update.

**Comment by wenlong-liu** [comment]
Thanks for your reply.  I tried to using linear stream flow in y-axis and the comparison of two types of y-axis is listed below. 

Although some work is still needed to polish the yticks in linear y-axis plot, it seems there are some benefits in linear y-axis.  The log-transformed y-axis tends to zoom in the low flow to show the overall distribution; however, it also kind of amplifies the significance of change in low flow.  In most cases, if we are focusing on the contamination export from streams, the higher flow tends to carry more chemicals, varying on watershed conditions.  Hence, users could have more flexibility to present their results by choosing the type of y-axis. 

![beta2_contour-log-transformed](https://user-images.githubusercontent.com/20285043/35632407-939abada-0674-11e8-9c57-1e72f7c648b2.png)

![beta2_contour_linear](https://user-images.githubusercontent.com/20285043/35632467-c2a55948-0674-11e8-8b13-432ff2d16dfa.png)

The data used in this post were downloaded from [Qian Zhang's website] (https://sites.google.com/site/qianzhangatjhu/publications).

-Wenlong
