### ISSUE TITLE
NaN results in runPairsBootAltC

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#149]
Laura:  Out of thousands of runs of runPairsBootAltC I have gotten the estimates on one or a few bootstrap replicates coming back as NaN values for both trend in concentration and trend in flux.  The program keeps running, but when it gets to the end it crashes as it tries to bring together all of the summary statistics on the bootstrap runs.  So, I may have done 500 replicates but at the end it just crashes and I get nothing.  It would be nice if we could do a fail safe method on this problem.

Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
I think we fixed this with the new updates. Now it will try for X successful runs, and if one or more aren't successful...it still finishes but gives a warning/message.
