### ISSUE TITLE
Error in wBT(eList, caseSetUp, fileName = "WBT.txt")

### ISSUE THREAD

**Issue by t4chandr** [USGS-R/EGRET#152]
Hello,

I keep getting the following error when I try running the WRTDS bootstrap test in both the interactive and batch modes.

Error in wBT(eList, caseSetUp, fileName = "WBT.txt") : 
  Error in resultSurvReg[k, ]: subscript out of bounds
/nNANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANAN

I'm using the following parameters:  year1=2007,  year2=2015, nBoot = 50, bootBreak = 9, blockLength = 50, and I have 224 samples for this site.

Has anyone else had this issue, or is this an issue with EGRETci? I'm a relatively new R user, and any help would be greatly appreciated!

**Comment by ldecicco-USGS** [comment]
I'm not 100% sure (and I'll try to check later this afternoon)...but I think that was a bug I fixed a little while back. Try first updating all your packages:

![update](https://user-images.githubusercontent.com/1105215/36981590-2e5e42e2-2053-11e8-86ce-03094c04e53f.png)

And if that doesn't work, then try updating `EGRETci` with the version on github:

```r
devtools::install_github("USGS-R/EGRETci")
```

If none of that helps, could you provide a script to reproduce your "eList"?

**Comment by t4chandr** [comment]
An update did the trick. Thank you so much!
