### ISSUE TITLE
Unkown error with wBT()

### ISSUE THREAD

**Issue by StefanoMezzini** [USGS-R/EGRET#193]
I receive the following error when running `wBT()` but am not sure why:
`Error in quantile.default(xFlux[1:iBoot], prob, type = 6): missing values and NaN's not allowed if 'na.rm' is FALSE:` 

Skipping the first year (1967) of the data set seems to avoid the issue. I have only ran into this error while using the data from one river but with multiple parameters that had data from 1967 or earlier, so I think the error must be due to some problem in the flow data. The same error occurs if I try running `wBT()` for a single year (`year1 == year2`).

I have attached a file with the flow data plus that of one of the parameters.

[EGRETci Debugging Data.txt](https://github.com/USGS-R/EGRET/files/2294141/EGRETci.Debugging.Data.txt)

**Comment by ldecicco-USGS** [comment]
Could you update (newest version on CRAN) EGRET and EGRETci and let me know if this is still happening? I know I added some  "na.rm = TRUE"'s recently.

**Comment by StefanoMezzini** [comment]
It works now, but all the flow estimates are `NA`

**Comment by ldecicco-USGS** [comment]
@StefanoMezzini if this is still an issue, open up a new ticket in the "EGRETci" repo:
https://github.com/USGS-R/EGRETci/issues
