### ISSUE TITLE
Trouble using HUC designation

### ISSUE THREAD

**Issue by nkday** [USGS-R/EGRET#195]
I would like find all nitrate samples in streams within a specified HUC designation.  I've tried this code: 

Sample <-readWQPSample(siteNumber="14050005", PatameterCd="00600", "1980-05-01","2012-05-01") 

 but get the following error:
Request failed [400]. Retrying in 1.2 seconds...
Request failed [400]. Retrying in 2.6 seconds...
Error: '' does not exist in current working directory ('C:/Users/nkday/Documents').

Seems like it's not looking on the WQP but in my working directory.  Also I can't find documentation on how to specify streams only.

THANKS!

**Comment by ldecicco-USGS** [comment]
You'll need to use dataRetrieval functions. By using the "parameterCd", you will be getting only USGS data. Maybe that's what you want, or you might want to figure out what "characteristicName" would best fit your analysis. Here's the code to get the USGS data:

```
library(dataRetrieval)
rawData <- readWQPdata(huc="14050005", 
                       pCode="00600", 
                       siteType="Stream",
                       startDateLo="1980-05-01",
                       startDateHi="2012-05-01")
```
So, that will get you total nitrogen data for a bunch of streams. EGRET is really only designed for 1 site. So...not sure what your end goal is, but that query will give it a start.
