### ISSUE TITLE
Different directory formats required

### ISSUE THREAD

**Issue by StefanoMezzini** [USGS-R/EGRET#200]
Hi,
Just wanted to note that while `readUserDaily()` and `readUserSample()` do not require a slash at the end of the folder directory string, `readUserInfo()` does. This difference can be a source of confusion among inexperienced R users. Here's an example for some additional clarity:

`Daily <- readUserDaily('~/Documents/ECCC Data', 'Assiniboine.flow.csv',)`
`Sample <- readUserSample('~/Documents/ECCC Data', 'Assin.Cl.csv')`

`Info <- readUserInfo('~/Documents/ECCC Data/', 'Assiniboine.INFO.csv')`

**Comment by ldecicco-USGS** [comment]
Thanks for the note! I will look to see if I can make it so either slash or no slash works for all functions.....

**Comment by ldecicco-USGS** [comment]
This will be fixed with #206
