### ISSUE TITLE
Consistency with readUserInfo

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/EGRET#206]
Both `readUserDaily()` and `readUserSample()` make a call to `readDataFromFile()`.  In `readDataFromFile`, one of the first lines executed is:

`totalPath <- file.path(filePath, fileName)`

In `readUserInfo()`, one of the first lines of code executed is:

`totalPath <- paste(filePath, fileName, sep = "") `

Note that the `..., sep="")` prevents the '/' being added to the `totalPath` variable and makes it so that `readUserInfo` returns the `File not found` msg.  An easy work around is to define two `filePath` variables, one without and trailing '/' for use with  `readUserDaily()` and `readUserSample()` and another with a trailing '/' for use with `readUserInfo`, but I think it would be more consistent (and appreciated) if the `paste` cmd inside `readUserInfo` was instead `..., sep="/")` (note the use of '/').  This would allow the user to define a single filePath variable that can be used in all three `readUser...` functions.

**Comment by ldecicco-USGS** [comment]
Agreed! I'll work that in right now. Thanks for the suggestion.
