### ISSUE TITLE
INFO hangs in R Commander

### ISSUE THREAD

**Issue by tofusal** [USGS-R/EGRET#213]
I've been gradually teaching myself EGRET/WRTDS using all of the great documentation available (thank you). I'm really comfortable working in the R Commander interface (currently on a Windows 10 box), so that's naturally where I started. I get through the readNWISSample and readNWISDaily data inputs just fine. Plotting works well. Then I get to INFO <- readNWISInfo(siteNumber, ParameterCd) and the app hangs. I have to kill the software with Task Manager. 

If I just run the tasks out of the main RGui R Console window, it works fine - I'm just less agile in that interface than in R Commander, so I was wondering if you knew what the source of the issue might be. 

I can keep making progress outside of R Commander, so this isn't a dead-in-the-water problem, just a productivity problem

**Comment by ldecicco-USGS** [comment]
If you turn off the interactive options, that will probably help:

```
INFO <- readNWISInfo(siteNumber, ParameterCd, interactive = FALSE)
```

 The VAST majority of our testing is done in RStudio. I'd highly recommend giving that platform a try, it's become very user-friendly over the years.

**Comment by tofusal** [comment]
Thanks. I think this call for help was months ago. I am using RStudio now. Thanks.
