### ISSUE TITLE
model estimation not converging

### ISSUE THREAD

**Issue by kimiakarimi** [USGS-R/EGRET#222]
I am testing a hypothesis in WRTDS. First, I used the observations from a site and got the predicted values for the period that I specified (which was the first day of 1983 until the end of 2017). Then I used these WRTDS estimations as "true" values and run it again for the true values. In other words, now I have observations for all day and I want to get WRTDS estimates of concentrations based on them. The problem is in one of the survival regression runs: the model is not converging in some of runs. There are suggestions that there could be something unusual about the data but I could not find anything, especially considering that I have observation for all the days in the period of modeling. I attached my inputs here. The flow unit is in m3/s so qunit=2 must be used. I appreciate if you could help me with this problem

[inputs.zip](https://github.com/USGS-R/EGRET/files/3070355/inputs.zip)

**Comment by rmhirsch49** [comment]
I took a look at your discharge input file and the dates were written as "1/1/83". This won't work, they need to be of the form 1/1/1983, or else 1983-01-01.  If you are still having problems you can send me your workspace (containing the eList) as an ".RData" file.  This makes it much easier for me to dig in and see what is going on.  Also, I don't understand why you want to estimate the model a second time with the ouputs of the first model.  Can you explain your intentions.  Feel free to do this via e-mail with me rhirsch@usgs.gov

Bob Hirsch
--
