### ISSUE TITLE
Daily concentration Estimates

### ISSUE THREAD

**Issue by mlrohal** [USGS-R/EGRET#225]
When using WRTDS is it possible to get a table of the daily estimated concentrations?

**Comment by ldecicco-USGS** [comment]
Indeed!
After you run the `modelEstimation` function, there will be several new columns in the "Daily" data.frame (which you can access from the eList). So estimated concentration is the "ConcDay" column:

```r
eList <- modelEstimation(eList)
Daily <- getDaily(eList)
Daily$ConcDay
```

**Comment by mlrohal** [comment]
Thanks Laura,

   I just have one more question for you.  I am new to R  is there a way to get that data into excel easily with each daily value being its own row?


Melissa

________________________________

**Comment by ldecicco-USGS** [comment]
Install the `openxlsx`  package, then:
```r
library(openxlsx)
write.xlsx(Daily, 'name-of-your-excel-file.xlsx')
```
(but don't be nervous about trying to do whatever it is you were thinking about directly in R!)
