### ISSUE TITLE
Formatting of plotHistogramTrend in EGRETci

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#228]
Laura: I was using the function plotHistogramTrend and the edges of the graphic seem all messed up.  The y-axis label runs off the edge of the plot, and the top line in the title is missing and the other two lines are pushed down.  Here are the plots.   Thanks.  Bob
![ConcTrend](https://user-images.githubusercontent.com/1170897/62291525-2abe7480-b432-11e9-8673-9618269fa841.png)
![Flux Trend](https://user-images.githubusercontent.com/1170897/62291526-2abe7480-b432-11e9-9de8-75f4148b8d64.png)

**Comment by ldecicco-USGS** [comment]
It all looked OK to me. Try running:
```r
dev.off()
```
before the `plotHistogramTrend` function to see if some graphic parameters were altered and propagated from a previous graph.
