### ISSUE TITLE
readWQPInfo not finding units

### ISSUE THREAD

**Issue by mturtora-USGS** [USGS-R/EGRET#24]
INFO <- readWQPInfo('21FLEECO_WQX-IMPRGR80', 'Phosphorus')

results in:
The units for the water quality data are:   .

**Comment by mturtora-USGS** [comment]
Thanks for taking care of the censored values issue.  It seems to be working.  

The interactive prompts are better but I have a few comments you may find helpful:

On a very minor point I caught a typo in the prompts:
     Enter the **concetration** units of Sample data

Between the two functions I've used (*readNWISInfo* for discharge and *readWQPInfo* for concentration data), it may be less confusing to simply state what units are required for discharge and concentration so that an unfamiliar user does not get the impression that the software will do conversions on the fly.  For discharge, the prompt is so obviously off that it almost didn't bother me.  Maybe some program logic could be added to make the prompt different for flow and stage.

The word "expects" in **Expected concentration units are mg/l.** is a little ambiguous.  A clearer word might be "required." Perhaps the idea is to keep those functions more generally useful in which case a strong warning would be more appropriate than hard-wiring the units.  If not, hard-wiring should be fine.

I thought perhaps "RTFM" might apply but, Table 3 in the user guide does not mention concentration.

Table 3 does suggest that drainage area is required, however, many in Florida are "Indeterminate" and the analysis seems to run ok without it.  The prompts are a little unclear though. A simple example might help.

**Comment by ldecicco-USGS** [comment]
Hmmm...yeah, table 3 doesn't mention anything on units. But the section (Selecting Units of Measurement, p 24) is our attempt to explain how units in EGRET work:
"The units for stored discharge values are m3/s, for concentration they are mg/L, for flux they are kilograms per day (kg/d), and for drainage area they are km2."

Reading your comment, I see it's not the greatest explanation, but it will have to do in that document. The help files however are something I can update a bit easier.

We use drainage area in 'runoff' calculations (`plotFlowSingle` and `printSeries`), so while it's useful to those functions, it's not critical in anything else. So, just don't use the `runoff` option in those functions with indeterminate drainage area sites.

**Comment by mturtora-USGS** [comment]
hmmm back... maybe you meant pg 14 of the first T&M version, looks like it's on page 15 of v2.0 (hot off the virtual press).  Haven't figured out how to fully view the edits yet but I did notice the word 'requires' in there.

**Comment by ldecicco-USGS** [comment]
Here's how the help page looks in development right now:

![info](https://cloud.githubusercontent.com/assets/1105215/6136557/35f49ac6-b137-11e4-9dab-7bf47c66474c.png)
