### ISSUE TITLE
Managing paStart and paLong parameters in runPairsBoot

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#245]
The output object of runPairsBoot (called pairsBootOut) needs to contain the values of paStart and paLong as attributes.  (They are attributes in the object that gets passed to runPairsBoot from runPairs).  Then, in plotHistogramTrend will contain the paStart and paLong information that is needed to form the period name that goes into the title of the graph.  So, changes need to be made in runPairsBoot and plotHistogramTrend.  There is nothing wrong with any of the computations it is only a matter of how it labels to outputs.  Right now, plotHistogramTrend is picking up its paStart and paLong information from eList$INFO$paStart and eList$INFO$paLong but these aren't what's driving the computations in either runPairs or runPairsBoot.

Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
Just fixed this over in EGRETci....
