### ISSUE TITLE
problem with yearEnd in plotConcHist

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#284]
This seems like a little thing, but I can't seem to get it to work right.  I'm using this command:

plotConcHist(eList, yearStart = 1985, yearEnd = 2003, plotFlowNorm = FALSE)

it works just fine.  I get data points out through water year 2003

Then I do the command:

plotConcHist(eList, yearStart = 1985, yearEnd = 2002, plotFlowNorm = FALSE)

But, I only get data points through water year 2001.  I should get them through 2002. I can't find a way to get a plot that ends with 2002.  It makes no sense to me.

I don't know how to attach a .RData file, so I'm sending you that file by email from my personal account.

Thanks.

Bob

**Comment by ldecicco-USGS** [comment]
Since we are labeling the graphs as "Water Year", I'm altering the code a bit to plot the points specifically for water year to be exactly at the water year...right now it's the decimal year (so 1990.249). For non-water year plots, I'll keep it at decimal year.
