### ISSUE TITLE
Need more options in plotConcHistBoot and plotFluxHistBoot

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#295]
Laura: I just noticed that in EGRETci, for these two functions we need to have the same kind of flexibility to turn on and off the annual results and the WRTDS-K results, if they exist.  Basically the same functionality that now exists in plotConcHist and plotFluxHist.  In these boot versions we should assume that we do want FN results and we do want the confidence intervals, it is the dots we want to be able to control.  Thanks.  If you can get to it quickly it would help me prepare for a talk I'm giving on Tuesday on Lake Erie.  But, if it takes longer I can do a work around.  Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
I should be able to get this up by this afternoon, so don't work on a work-around quite yet!
