### ISSUE TITLE
Partial years in plotConcHist and plotFluxHist

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#296]
Laura: I think I wrote you an e-mail about this a while back.  The problem is this.  When the first or last year of data in the eList$Daily data frame does not cover the full period of analysis (e.g. we are using water year, but the last year of data ends at the end of June), these functions plot the averages for the set of days it has and that often causes a sharp upturn or downturn at the front end or back end of the plot.  The issue is also there in tableResults() and in EGRETci in plotConcHistBoot() and plotFluxHistBoot().  Thanks.

Bob

**Comment by ldecicco-USGS** [comment]
Right! I sort of remember talking about this.... Does this look like a reasonable reproducible example:

```r
library(EGRET)
eList <- Choptank_eList
eList <- setPA(eList, paStart = 1, paLong = 12)
plotConcHist(eList, yearStart = 1979, yearEnd = 2011)
```
which results in:
![image](https://user-images.githubusercontent.com/1105215/103661041-e511af80-4f33-11eb-9255-5775663acd2e.png)

So right now, we check in `setupYears` if we have at least 90% of the *reported* days with data (not NA). Do we want to change that FROM:
```r
    # need to see if the data frame for the year has enough good data
    counter <- ifelse(is.na(DailyYear$ConcDay),0,1)

    # if we have NA values on more than 10% of the days, then don't use the year
    if (length(counter) > 0){
      good <- sum(counter) / length(counter) > 0.1
    } else {
      good <- FALSE
    } 
```
to:
```r
    firstDay_i <- localDaily$Date[localDaily$MonthSeq == startMonth][1]
    lastDay_i <- tail(localDaily$Date[localDaily$MonthSeq == stopMonth], n = 1)
    
    numDaysInYear <- as.numeric(lastDay_i - firstDay_i)

    if (length(counter) > 0){
      good <- sum(counter) / numDaysInYear > 0.1
    } else {
      good <- FALSE
    }  

```
That will produce:
![image](https://user-images.githubusercontent.com/1105215/103690585-91668c80-4f5a-11eb-9ae7-438ec108897f.png)

I think this is correct, and running the long tests right now. Do we want to warn/message the user that the years they ask for aren't on the graph?

**Comment by rmhirsch49** [comment]
Laura: The more I think about it, it seems to me that we would want to see something that says if we don’t have something like 99% of the days in the period having actual values then we discard it from the set of annual results.  In fact, I think the current code is really problematic.  Let’s say that paStart = 1, paLong = 1 (so we are only looking at Jaunary), and in the year 2020 the data frame DailyYear for the year 2000 only had a ConcDay value for January 1 and nothing after that (i.e. that was just simply the end of the record).  In this case counter would be 1, and length(counter) would also be 1, so we would say that it is fine to use it.  But it shouldn’t be fine to use it.  Somehow, I think we want the code to know how many days we could have valid data in that PA for that year and then how many days we actually do have values.  And the latter number should be very close to or equal to the former.  In my little example here, January 2020 could have 31 values, but it only had 1 value, so we should be saying don’t put it in the annual results.

Bob

**Comment by ldecicco-USGS** [comment]
I agree, the current code is problematic. Have a look at what I've got here (the changes start at line 74 and go on within that function):

https://github.com/ldecicco-USGS/EGRET/blob/master/R/setupYears.R#L74

**Comment by rmhirsch49** [comment]
This code is different from what you sent today.  In this one I see where you are computing counter, but I still don’t see the requirement that the number of good days needs to be all (or virtually all) the days in the year.

**Comment by ldecicco-USGS** [comment]
I think this is all fixed...we'll re-open if we find more problems.
