### ISSUE TITLE
readUserDaily issue

### ISSUE THREAD

**Issue by jmduncan** [USGS-R/EGRET#297]
I've been trying to use WRTDS for a long-term research watershed not operated by USGS. I'm running into issues with readUserDaily. The file is read in OK, but not converted to a Daily dataframe. 
Daily <-readDataFromFile(filePath,fileName, separator=",")
head(Daily)
        Date     Qdaily
1 1972-10-01 0.04500000
2 1972-10-02 0.04783175
3 1972-10-03 0.03154123

It should have additional varaiables calculated, right?
When I try to run eList, it causes a problem. 
> eList <- mergeReport(INFO, Daily, Sample)

 Discharge Record is 17166 days long, which is 47 years
 First day of the discharge record is 1972-10-01 and last day is 2019-09-30
 The water quality record has 2698 samples
 The first sample is from 1972-10-02 and the last sample is from 2019-05-28
 Discharge: Minimum, mean and maximum 0.000173 0.435 24.4
 Concentration: Minimum, mean and maximum 0.005 0.46 5.6
 Percentage of the sample values that are censored is 0 %

Please double check that the Daily dataframe is correctly defined.
Error in `[.data.frame`(Daily, , c("Date", "Q", "LogQ")) : 
  undefined columns selected

What am I missing? Could it be an issue with populateDaily? Or could this be a conflict with another library?
Any insights/advice would be most appreciated!

**Comment by ldecicco-USGS** [comment]
Are you using readDataFromFile, or readUserDaily?

Like this:
```
Daily <- readUserDaily(filePath,fileName, separator=",")
```

**Comment by jmduncan** [comment]
I tried it both ways. readUserDaily and readDataFromFile per the vignette.

**Comment by ldecicco-USGS** [comment]
What do you see when you run:
```
Daily <- readUserDaily(filePath,fileName, separator=",")
head(Daily)
```

**Comment by jmduncan** [comment]
I closed R, started a new session, and I'm off to the races. Something must have gotten conflated between current and old syntax. Thanks for the help!

> Daily.test<-readUserDaily(filePath, fileName, separator = ",")
>head(Daily.test)
        Date            Q Julian Month Day  DecYear MonthSeq waterYear i      LogQ Q7
1 1972-10-02 0.0013544444  44834    10 276 1972.752     1474      1973 1 -6.604364 NA
