### ISSUE TITLE
One more fix needed to setupYears

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#299]
Laura: I was digging into your new version of setupYears because of some other stuff I was doing.  I think there is an error in one line of code.  Please see if I'm right.  The line should say:

numDaysInYear <- as.numeric(lastDate - firstDay_i + 1)

Without this change I was finding that full years (non leap year) had numDaysInYear were 364.  But please check it over to make sure it is correct.  Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
I just fixed this and pushed it up to the main "USGS-R/EGRET" repo, so installing like this:
```r
remotes::install_github("USGS-R/EGRET")
```
will get the new setupYears code.
