### ISSUE TITLE
Fix plotConcQSmooth

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#30]
minConc not working right

**Comment by ldecicco-USGS** [comment]
Hello Laura,

I'm trying to run the command below and nothing happens to the plot when I run the second command, which has the additional concMin=7 argument.

plotConcQSmooth(eList, date1, date2, date3, qBottom, qTop, qUnit=1,  printLegend=FALSE)
plotConcQSmooth(eList, date1, date2, date3, qBottom, qTop, qUnit=1,  printLegend=FALSE, concMin=7)

I also tried modifying the function to accomplish the same end.  Inside plotConcQSmooth(), I changed the following line that appears inside the genericEGRETDotPlot:

ylim = c(yInfo$bottom, yInfo$top)

to:

ylim = c(7, yInfo$top)

My thinking was that I could force the lower y-axis limit to be at 7.  However, this produced an error message that I wasn't sure how to handle?  Because I didn't do anything with qConst, I'm not sure what the issue is?

plotConcQSmooth(eList, date1, date2, date3, qBottom, qTop, qUnit=1,  printLegend=FALSE)
#Error in plotConcQSmooth(eList, date1, date2, date3, qBottom, qTop, qUnit = 1,  : 
# object 'qConst' not found
 
In a second attempt, I tried changing the following line from:

yInfo <- generalAxis(combinedY, maxVal = concMax, minVal = concMin, 

to:

yInfo <- generalAxis(combinedY, maxVal = concMax, minVal = 7, 

but this produced the same error as before?  Is there another option available to force the plot to honor concMin?  

Thanks Eric.

**Comment by ldecicco-USGS** [comment]
The second half of this issue is because the sysdata.rda is not exported. I will fix that bug in the next release. The first half should be fixed.

**Comment by ldecicco-USGS** [comment]
@rmhirsch49 : we've had concMin as an argument in this function as long as it's been in EGRET. However, as Eric points out, it doesn't work for linear concentration axes (because we force it to zero unless the concentration is plotted in the log scale...then it works). 

We include concMin in:
`plotConcQ`
`plotConcQSmooth`
`plotConcTime`
`plotConcTimeSmooth`

I think it is because all of these functions historically had corresponding log functions (where a concMin argument makes sense). The user might want to specify the minConc for log plots, but not linear. 

Based on #32, I assume that we should keep the behavior the same as it currently stands (concMin is ignored if linear concentration access) but improve the documentation. Currently, it reads:

#' @param concMin numeric value for lower limit on concentration shown on the graph, default = NA (which causes the lower limit to be set automatically, based on the data)

would change to something like:

#' @param concMin numeric value for lower limit on concentration shown on the log graph, default = NA (which causes the lower limit to be set automatically, based on the data). This value is ignored for linear scales, using 0 as the minimum value for the concentration axis.

**Comment by rmhirsch49** [comment]
Yes: I think you have that right.  Bob

On Mon, Feb 9, 2015 at 3:33 PM, Laura DeCicco <notifications@github.com>
wrote:

> @rmhirsch49 <https://github.com/rmhirsch49> : we've had concMin as an
> argument in this function as long as it's been in EGRET. However, as Eric
> points out, it doesn't work for linear concentration axes (because we force
> it to zero unless the concentration is plotted in the log scale...then it
> works).
>
> We include concMin in:
> plotConcQ
> plotConcQSmooth
> plotConcTime
> plotConcTimeSmooth
>
> I think it is because all of these functions historically had
> corresponding log functions (where a concMin argument makes sense). The
> user might want to specify the minConc for log plots, but not linear.
>
> Based on #32 <https://github.com/USGS-R/EGRET/issues/32>, I assume that
> we should keep the behavior the same as it currently stands (concMin is
> ignored if linear concentration access) but improve the documentation.
> Currently, it reads:
>
> #' @param <https://github.com/param> concMin numeric value for lower
> limit on concentration shown on the graph, default = NA (which causes the
> lower limit to be set automatically, based on the data)
>
> would change to something like:
>
> #' @param <https://github.com/param> concMin numeric value for lower
> limit on concentration shown on the log graph, default = NA (which causes
> the lower limit to be set automatically, based on the data). This value is
> ignored for linear scales, using 0 as the minimum value for the
> concentration axis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/30#issuecomment-73584495>.
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************

**Comment by ldecicco-USGS** [comment]
Pushed the updated documentation to USGS-R/EGRET
