### ISSUE TITLE
Minimum Data Requirement Guidelines (minNumObs, minNumUncen)

### ISSUE THREAD

**Issue by elp94** [USGS-R/EGRET#301]
Hi there,

I've been struggling to find the minimum data requirements for using WRTDS. I've found documentation that indicate WRTDS works best with 100+ observations, and that <50 observations will be in the "dangerous range" for reliability. Would 60 observations be an acceptable cut-off for minimum sample size?

I've also been unable to find any documentation for the maximum number of allowable censored samples for WRTDS (or the minimum number of uncensored samples). The default values for minNumObs and minNumUncen in modelEstimation suggest that WRTDS could run with 50% censored values. Is there any insight to how reliable the regression would be for a dataset that is more than 50% censored? And do you have any recommendations for the maximum percent of censored data that is allowable?

Any guidance or insight that you could provide would be very much appreciated!! Thank you!

**Comment by rmhirsch49** [comment]
The minimums depend on what you want to do.  If it is simply to get an overall estimate of average flux or average concentrations then 50 samples would be ok.  But, if you are interested in trends it is preferable that you be at more than 100 samples.  For the analysis of trends you can use the tools in EGRETci to see whether your estimates of trend are really meaningful.  If the trend was very strong, then you might be able to get a significant result with even somewhat fewer than 100.  This would be the kind of thing you might expect to see when there is some major point source that has had substantial improvement over the period of record, but where non-point sources are the main driver of water quality, it would be pretty unusual to get a highly significant result with 100 samples.

We don’t have any really specific guidance on the amount of uncensored data.  I would certainly say that if you were interested in trends and you had only 100 total samples and 50 or more of them were censored I would say that it is unlikely that you will get a very meaningful result.  But, here again, the tools in EGRETci can help you figure that out.

I think that the important point is that there are no hard and fast rules on absolute minimums (although you have to adjust minNumObs and minNumUncen to get it to run in some cases) but if all you have is 60 samples, you may want to go with a simpler approach (e.g. Seasonal Kendall for trends).   But, if you are working with several sites and/or several constituents and many of them do have more plentiful data (> 100 values) then it might make sense to use WRTDS on all data sets, recognizing that a convincing trend result is unlikely with a small amount of data.

I hope that helps.

Bob Hirsch

**Comment by elp94** [comment]
Thank you so much for the response, Bob! It was really helpful and informative, especially for a newbie like me. I appreciate it!
