### ISSUE TITLE
Compare GFN results to SFN results

### ISSUE THREAD

**Issue by mgm-cincy** [USGS-R/EGRET#304]
By using the defaults with modelEstimation, runPairs, runSeries, and runGroups that gives Generalized Flow Normalization (GFN) output, correct? Do I get SFN results by changing in modelEstimation the arguments of windowY, windowQ, and windowS to all equal 0?  I tried that with the Choptank example and got the "Problem converging" error.  For runPairs, runSeries, and run Groups setting the windowSide = 0 would produce stationary flow normalization (SFN).  What arguments are used to specify SFN output with modelEstimation?
Thanks,
Mike McManus

**Comment by rmhirsch49** [comment]
The function modelEstimation( ) can only do Stationary Flow Normalization.  You should probably leave the other arguments at their defaults and run modelEstimation( ) if you want SFN.  If you use runPairs( ), runGroups( ), or runSeries( ) you can do SFN by setting windowSide = 0 (and you should probably leave the other arguments at their default values).
