### ISSUE TITLE
Printout part of mergeReport seems to have vanished

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#314]
I'm working on a new example of putting data into EGRET for my workshop session for NWQMC and I ran mergeReport (using the code on github) and I didn't get the stuff printing to the console like min mean and max concentration, min mean and max Q number of days in each record, how many samples, how many less thans.  Don't know what happened to that stuff but I hope you can put it back in.

Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
Those numbers come from `dataOverview`. Not sure why it wouldn't print out unless there was a `sink` call (which takes the output and writes it to a file. That being said.....I was thinking it would be nice to convert the output to a "message". The difference between `cat` and `message` is that a user could turn off the `message` (whereas they don't have that control on `cat`). This would be nice in the Yeti logs for example when we've got hundred/thousands of lines of output that summarize the data.

**Comment by rmhirsch49** [comment]
I figured out that the dataOverview printing doesn't happen when there is a warning message about some days having multiple samples.  When this message doesn't show up the dataOverview comes out the way it should
