### ISSUE TITLE
Small changes in titles to plotConcHist and plotFluxHist

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#318]
In plotConcHist, if we have plotGenConc = TRUE then in the third line of the title it should say "(red dots)" and not "(dots)" -- without that it is confusing because we have red dots and black dots, we need to distinguish them.

Same issue in plotFluxHist, if we have plotGenFlux = TRUE we should do that same change to the title.

Thanks.

**Comment by ldecicco-USGS** [comment]
Here is my working examples:
```r
plotConcHist(eK, yearStart, yearEnd, plotGenConc = TRUE)
```
![image](https://user-images.githubusercontent.com/1105215/113439703-b2e7e080-93b0-11eb-80f3-c88600ec2d78.png)

```r
plotConcHist(eK, yearStart, yearEnd, plotGenConc = TRUE, plotAnnual = FALSE)
```
![image](https://user-images.githubusercontent.com/1105215/113439829-e6c30600-93b0-11eb-8365-0042c115eabb.png)

```r
plotConcHist(eK, yearStart, yearEnd, plotGenConc = FALSE, plotAnnual = FALSE)
```
![image](https://user-images.githubusercontent.com/1105215/113439883-00644d80-93b1-11eb-81da-faddb8203a36.png)

```r
plotConcHist(eK, yearStart, yearEnd, plotGenConc = TRUE, plotAnnual = TRUE, plotFlowNorm = FALSE)
```
![image](https://user-images.githubusercontent.com/1105215/113439964-2a1d7480-93b1-11eb-8c82-476ca78c7c64.png)

```r
plotConcHist(eK, yearStart, yearEnd, plotGenConc = FALSE, plotAnnual = TRUE, plotFlowNorm = FALSE)
```
![image](https://user-images.githubusercontent.com/1105215/113440238-a57f2600-93b1-11eb-93f8-f4f3a6e7deaf.png)

```r
 plotConcHist(eK, yearStart, yearEnd, plotGenConc = TRUE, plotAnnual = FALSE, plotFlowNorm = FALSE)
```
![image](https://user-images.githubusercontent.com/1105215/113440224-97c9a080-93b1-11eb-928e-b3325d57ccbb.png)


Does that look about right?

**Comment by rmhirsch49** [comment]
I think it looks great.  Thanks.  Bob
