### ISSUE TITLE
Problems with the function saveResults() in EGRET

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#323]
Laura:  Two things seem to have happened.  The first is that the code now calls for the name of the file to use INFO$shortName.  It should be INFO$staAbbrev.  The other problem is that it generates a message that says ".Deprecated("base R's saveRDS")". This is confusing and I don't think that the saveRDS function would work, because it doesn't have a way to give the file a meaningful name as we have had in the past.  I would like to go back to the original code for this.  Thanks.

Bob

**Comment by ldecicco-USGS** [comment]
Big issue is we should use INFO$staAbbrev instead of shortName
