### ISSUE TITLE
Export daily concentrations

### ISSUE THREAD

**Issue by kqasem** [USGS-R/EGRET#327]
Hey,
Thanks for the great tool. I am using the WRTDS estimation tool and was able to successfully produce results. How can I export the estimated daily concentration as a csv file?

Is there a way to export the "daily" estimation in the following format?

date; discharge; concentration?

Also, do you recommend the tool for predicting fecal coliform?

Best,
Karoline

**Comment by ldecicco-USGS** [comment]
The daily concentrations are in the "Daily" data frame within the eList. So, if you ran the model like this:

```
eList <- modelEstimation(eList)
Daily <- eList$Daily
#Just date, discharge, conc:
daily_small <- Daily[, c("Date", "Q", "ConcDay")]
#write to a csv:
write.csv(daily_small, file = "daily.csv", row.names = FALSE)
```
ConcDay is the modeled concentration, FNConc is another column in the Daily data frame, it's the flow-normalized concentration.
