### ISSUE TITLE
duplicated values

### ISSUE THREAD

**Issue by kimiakarimi** [USGS-R/EGRET#342]
Hello,

My question is regarding multiple observations from a single day. I believe the _removeDuplicates_ function only removes identical samples from a single day but how does the regression handles if there are two or more non-similar observation from one day?

**Comment by rmhirsch49** [comment]
You are correct about how removeDuplicates work.  The regression uses all of the data in the Sample data frame no matter how many samples happen on the same day.  The weights on each sample are computed without regard to the number of samples on that day.  I hope that answers your question.

One could argue for other ways of doing this but the coding was designed assuming that the sampling is not highly frequent (e.g. say less than 50 samples per year), but it works for any frequency.

Bob Hirsch

From: kimiakarimi ***@***.***>
Date: Thursday, April 21, 2022 at 5:46 PM
To: USGS-R/EGRET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-R/EGRET] duplicated values (Issue #342)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hello,

My question is regarding multiple observations from a single day. I believe the removeDuplicates function only removes identical samples from a single day but how does the regression handles if there are two or more non-similar observation from one day?
