### ISSUE TITLE
Making simple maps of sites 

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#49]
It would be nice to have an ability to draw a quick map of the location of a site that is contained in eList$INFO using the latitude and longitude.  Even nicer would be an ability to draw the watershed boundary shape file for that site as well.  I know how to do the first, but we need to work on the second one.  I plan to start up a vignette that will walk people through it.

**Comment by ldecicco-USGS** [comment]
https://github.com/USGS-R/hydroMaps

Still a work-in-progress, but has the functionality.

**Comment by rmhirsch49** [comment]
Laura: I'd like to see if I can help by just adding some kind of
introduction to the vignette to add some of the motivation for this
functionality.  If you can send me the proper version of the rMarkdown for
it I would like to see if I can add something useful to it.  Then, the next
question is how to tell people about it.  There is a lot of interest.  This
would be a great blog item if we can get the blog thing going.

Thanks.

Bob

On Tue, May 10, 2016 at 10:00 AM, Laura DeCicco <notifications@github.com>
wrote:

> Closed #49 <https://github.com/USGS-R/EGRET/issues/49>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/49#event-655798002>
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************
