### ISSUE TITLE
Wording of a message in populateDaily

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#54]
This seems like a small issue, but it is just a choice of words that means something very specific to USGS hydrologists.  There is a message that populateDaily generates that says ""discharge measurements are not reported (NA's). \nMany of the EGRET functions will not work with missing discharge measurements."  The word "measurements" should be replaced with the word "values" -- The reason is that in our lingo, the word "measurements" means the calibration measurements that are made at the streamgage -- there may be only a dozen or couple of dozen per year.  What is delivered by the NWIS daily values service is the daily discharge value that is computed from the stage data.  It doesn't deliver what we call "measurements".  

Not a big deal, just something to fix the next time you make other changes to EGRET. Thanks.  Bob

**Comment by jread-usgs** [comment]
Here you go: 
https://github.com/USGS-R/EGRET/blob/22f461aff8cd4cb5573597c0e66b50265a3679f9/R/populateDaily.r#L121
