### ISSUE TITLE
ND's reported as 0's from WQ Warehouse

### ISSUE THREAD

**Issue by jmacart** [USGS-R/EGRET#68]
I am seeing data which is stored as less thens come up as 0's using dataRetrieval.

> library(dataRetrieval)
> library(EGRET)
> siteNumber<-"MNPCA-S000-154"
> characteristicName<-"Inorganic nitrogen (nitrate and nitrite)"
> startDate<-"1976-01-01"
> endDate<-"2010-12-31"
> Sample<-readWQPSample(siteNumber,characteristicName,startDate,endDate)
Deleted Rows:
      dateTime ConcLow ConcHigh Uncen
189 2004-10-11       0        0     1
190 2004-11-16       0        0     1
191 2005-02-16       0        0     1
192 2005-03-17       0        0     1
193 2005-04-27       0        0     1
194 2005-05-18       0        0     1
195 2005-06-06       0        0     1
196 2005-07-24       0        0     1
197 2005-08-17       0        0     1
198 2005-09-26       0        0     1
201 2007-02-12       0        0     1
204 2007-05-14       0        0     1
205 2007-06-24       0        0     1
206 2007-08-01       0        0     1
207 2007-08-27       0        0     1
208 2007-09-17       0        0     1
211 2009-04-07       0        0     1
212 2009-04-14       0        0     1
213 2009-04-22       0        0     1
215 2009-05-06       0        0     1
216 2009-05-13       0        0     1
217 2009-05-20       0        0     1
218 2009-06-11       0        0     1
219 2009-06-23       0        0     1
220 2009-07-14       0        0     1
221 2009-07-29       0        0     1
222 2009-08-11       0        0     1
223 2009-08-26       0        0     1
224 2009-09-15       0        0     1
225 2009-10-07       0        0     1
226 2009-10-13       0        0     1
227 2009-11-03       0        0     1
228 2009-11-10       0        0     1
229 2009-11-17       0        0     1
230 2009-12-01       0        0     1
232 2010-03-23       0        0     1
233 2010-04-19       0        0     1
234 2010-05-25       0        0     1
235 2010-06-14       0        0     1
236 2010-07-20       0        0     1
237 2010-08-23       0        0     1
238 2010-09-20       0        0     1
Warning message:
In compressData(data, interactive = interactive) :
  Deleted 42 rows of data because concentration was reported as 0.0, the program is unable to interpret that result and is therefore deleting it.

**Comment by ldecicco-USGS** [comment]
Sorry for the late response. I looked into it a bit. Those dates are below the detection limit, but no detection limit is reported. So, EGRET doesn't know what to do, and ends up deleting those rows. You can look at the raw data like this:

```
library(dataRetrieval)
library(EGRET)
siteNumber<-"MNPCA-S000-154"
characteristicName<-"Inorganic nitrogen (nitrate and nitrite)"
raw <- readWQPqw(siteNumber,characteristicName,startDate,endDate)
```

If you sort by date (so the first row is 2010-09-20), you'll see the text "Present below quantification limit" in the column ResultDetectionConditionText. But NA in the column DetectionQuantitationLimitMeasure.MeasureValue. So, there's not enough information to do much with that data. Sound right?

**Comment by jmacart** [comment]
Thank you I will talk to our database people about why those are not being stored correctly.
