### ISSUE TITLE
blankTime and plotFluxHist or plotConcHist function 

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#72]
There is a problem when a user sets up a blankTime period that has a start and/or end date that is not alligned with the period of analysis for these graphs (it might also apply to some of the tables).  

Say I do this:
plotFluxHist(eList)
startBlank <- "2000-01-01"
endBlank <- "2003-12-31"
eList <- blankTime(eList,startBlank,endBlank)
plotFluxHist(eList)

The result we would like is that the two graphs look exactly the same but the latter one will just have a part of the green line vanish and several dots vanish, but no values get changed.  In fact, what happens is that the partial water years that haven't been blanked out still figure in so there can be a sharp bend in the green curves next to the break and the data points near the break have moved around.  

What needs to happen is that these functions plotConcHist and plotFluxHist need to be modified so that if there are any NA values in a given year within the PA it won't compute a value for that year and it will be NA for purposes of the graph.  

I've done a little test case and can see that the problem exists also in setupYears, tableResults and tableChange as well.

At first glance I thought the solution was just to make sure that the blankStart and blankEnd defined a water year, but then I realized that the user may want to look at calendar year or some other PA and the problem really wouldn't be solved.  

I think all of this can be fixed with a fix to setupYears (because all of these functions that show the problem depend on setupYears for their annual values).  

I think the fix is simply this:  In setupYears the line that says:

good <- (sum(counter) > 25)

should actually say

good <- (sum(counter) == length(counter))

I think the sum(counter) > 25 is a relic from when we were doing this summing by month and I wanted there to be at least 25 valid days in the month to make it work).

Probably needs to be fixed on CRAN and on our internal version of EGRET

Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
Will do, I want to submit an update to `dataRetrieval` soon, and can get this worked in too.

I think a similar question I have:

**Comment by ldecicco-USGS** [comment]
It looks like for calculating minimums, paStartLow is set to 4 for a water year, but for all other statistics, it's set to 10.

**Comment by rmhirsch49** [comment]
Laura: I don't understand your email.  Where does paStartLow show up?  What
function is that in?

Bob

On Thu, Feb 25, 2016 at 12:21 PM, Laura DeCicco <notifications@github.com>
wrote:

> It looks like for calculating minimums, paStartLow is set to 4 for a water
> year, but for all other statistics, it's set to 10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/72#issuecomment-188887814>.
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************

**Comment by rmhirsch49** [comment]
I just went to GitHub and see the issue you are referring to in the flow
history stuff.

Here's the answer.  The standard convention in hydrology is that for
computing annual maxima we always use the water year.  The logic for that
is that we are unlikely to find ourselves having the maximum flow of year i
being in late September and the maximum of year i+1 being in early October,
because the Fall is usually a time of low flow.  We want to avoid that
situation, because we would be effectively counting the same event twice in
the time series of annual maxima.  Conversely, when computing low flow
statistics we use the "climatic year" which runs April to March, so paStart
would be 4.  It is unlikely that a major low-flow event will span from
March to April.  We discuss this in the User Guide (bottom half of page 16).

Bob

On Thu, Feb 25, 2016 at 1:21 PM, Hirsch, Robert <rhirsch@usgs.gov> wrote:

> Laura: I don't understand your email.  Where does paStartLow show up?
> What function is that in?
>
> Bob
>
> On Thu, Feb 25, 2016 at 12:21 PM, Laura DeCicco <notifications@github.com>
> wrote:
>
>> It looks like for calculating minimums, paStartLow is set to 4 for a
>> water year, but for all other statistics, it's set to 10.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-R/EGRET/issues/72#issuecomment-188887814>.
>>
>
>
>
> --
>
> ************************************************************
> * Robert M. Hirsch
> * Research Hydrologist
> * 432 National Center                     rhirsch@usgs.gov
> * U.S. Geological Survey                ph  703-648-5888
> * Reston, VA 20192         http://profile.usgs.gov/rhirsch
> *************************************************************
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************
