### ISSUE TITLE
GRAN Install - package load error

### ISSUE THREAD

**Issue by acanion** [USGS-R/EGRET#73]
I installed EGRET from the GRAN repo and when I load the package I get the following error:

> library(EGRET)
Error : object ‘col_number’ is not exported by 'namespace:readr'
Error: package or namespace load failed for ‘EGRET’

**Comment by ldecicco-USGS** [comment]
Hmm...my first guess is that you should try updating your packages (especially `readr`) and try again. I'll try to figure out what version of `readr` *does* start exporting col_number, and update the requirement in the DESCRIPTION file. Thanks for the note, and let me know if updating doesn't help.

**Comment by ldecicco-USGS** [comment]
Looks like `readr` needs to be >= 0.1.1.9000

**Comment by acanion** [comment]
I updated readr and now it works.  Sorry for bothering you with such an easy problem

**Comment by ldecicco-USGS** [comment]
Don't apologize! That should be a requirement in the `dataRetrieval` DESCRIPTION file...and will be in the next release. Thanks again!
