### ISSUE TITLE
Useful enhancement to plotContours and plotDiffContours

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#74]
Laura: this is something that has come up in my interactions with some users and I share their concern.  Right now, the y-axis of these two kinds of contour plots are constrained to start and end with discharge values such as 1, 2, 5, 10, 20, 50,...  There are times when it would be nice to be able to pick any arbitrary value for the lower or upper bound on the axis.  Sometimes when the selected limits are too wide apart, part of the figure plots as white space (because there are no data in that region in the surfaces object).  That would be nice to avoid.  But also, sometimes we have situations where perhaps a maximum of 20 cuts off too much of the relevant high discharge space, but 50 goes to far and shows results that are very unlikely and thus not very meaningful and the user may want to set the limit at say 30 or 40.  I would still like to keep the tick mark values simple (1, 2, 5, 10, etc.) but allow it to go to any value.  This is similar to a change you made a while back in plotQTimeDaily so that the lower bound could be at any value selected.  Thanks.  Bob

**Comment by ldecicco-USGS** [comment]
For both contour plots, I added that functionality. So, to test it out to see if you like it:

```
devtools::install_github("USGS-R/EGRET")
eList <- Choptank_eList
yearStart <- 2001
yearEnd <- 2010

#qTop and qBottom now default to 5 and 95% of discharge:
plotContours(eList, yearStart,yearEnd)

#Setting them will provide exact limits + "pretty" ticks
qBottom <- 0.5
qTop<- 22
plotContours(eList, yearStart,yearEnd,qBottom,qTop)

#Something we've always (ish?) been able to do is provide the exact yTicks:
yTicksModified <- c(.1,1,10,25)
plotContours(eList, yearStart,yearEnd,qBottom,qTop,yTicks=yTicksModified)

```

**Comment by rmhirsch49** [comment]
Laura:  I guess I never noticed the yTicks argument.  I actually think that
we already have the functionality we need without any change in the code.
I just tried the original code on a problem and I think it works great.  I
don't see the need to change.  However, I think it would be worthwhile to
add some information to the help page.

For qBottom maybe the help info should have added to the end of it: "... if
yTicks are specified, then the first value of yTicks becomes the lowest
discharge shown on the figure."

Similarly: For qTop  the help info should have added to the end of it: "...
if yTicks are specified, then the last value of yTicks becomes the highest
discharge shown on the figure."

For yTicks the help should say "...will be plotted in log space.  (for
example yTicks = c(3, 5, 10, 20, 50, 100, 200, 400).  The first and last
values determine the range of the y axis.  If NA, the tick marks will be
automatically generated."

What do you think?

Thanks for working on this.

Bob

On Wed, Mar 2, 2016 at 2:20 PM, Laura DeCicco <notifications@github.com>
wrote:

> For both contour plots, I added that functionality. So, to test it out to
> see if you like it:
>
> devtools::install_github("USGS-R/EGRET")
> eList <- Choptank_eList
> yearStart <- 2001
> yearEnd <- 2010
>
> #qTop and qBottom now default to 5 and 95% of discharge:
> plotContours(eList, yearStart,yearEnd)
>
> #Setting them will provide exact limits + "pretty" ticks
> qBottom <- 0.5
> qTop<- 22
> plotContours(eList, yearStart,yearEnd,qBottom,qTop)
>
> #Something we've always (ish?) been able to do is provide the exact yTicks:
> yTicksModified <- c(.1,1,10,25)
> plotContours(eList, yearStart,yearEnd,qBottom,qTop,yTicks=yTicksModified)
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/74#issuecomment-191382358>.
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************
