### ISSUE TITLE
A small bug in the function wordLike in the EGRETci package

### ISSUE THREAD

**Issue by rmhirsch49** [USGS-R/EGRET#77]
Laura: I was looking at a result the the Chesapeake Bay folks had and ran the wBT code on their data.  What I found was a contradiction in the descriptions of the likelihood of uptrends and downtrends.  What I got was "Upward trend in flux is about as likely as not" but "Downward trend is likely" -- this makes no sense.  I see the error in the code.  I'm quite sure it was MY error.  There is a line in the code that says:

breaks <- c(0, 0.05, 0.1, 0.33, 0.66, 0.9, 0.95, 1)

It should say

breaks <- c(0, 0.05, 0.1, 0.33, 0.67, 0.9, 0.95, 1)

So, not a big deal, but I would like to have you make the change to EGRETci on CRAN and GRAN.  Thanks.

Bob

**Comment by ldecicco-USGS** [comment]
So, just change the 0.66 to 0.67?

**Comment by rmhirsch49** [comment]
Yep.  Just one digit.  In my original coding my mind just saw symmetry
between 0.33 and 0.66.  Nope.  The symmetric values are 0.33 and 0.67.

Bob

On Tue, Apr 12, 2016 at 5:25 PM, Laura DeCicco <notifications@github.com>
wrote:

> So, just change the 0.66 to 0.67?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/77#issuecomment-209109259>
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************
