### ISSUE TITLE
readNWISDaily oddity

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/EGRET#84]
As the attached screen capture will show, a gage in western WA (Gage ID = 12010000) apparently has two records under p-code 00060.  The first has the nuance "STILLING WELL" and stops at the end of WY2003.  The second instance of 00060 is ongoing.  When I run readNWISDaily(), it grabs the dataset ending in WY2003.  Is there a way to have it instead grab the dataset that is ongoing?

`siteNumber <- "12010000"`
`startDate <- ""`
`endDate <- ""`
`Daily <- readNWISDaily(siteNumber,'00060',startDate,endDate)`

![two_00060_codes](https://cloud.githubusercontent.com/assets/3236576/15801477/26da88a0-2a4b-11e6-9dc8-601a75842bb7.png)

**Comment by ldecicco-USGS** [comment]
Here you go:

```
library(EGRET)
library(dataRetrieval)

siteNumber <- "12010000"
startDate <- ""
endDate <- ""

obs.url <- constructNWISURL(siteNumber,"00060",startDate,endDate,"dv",statCd="00003", format = "tsv")

rawData <- importRDB1(obs.url, asDateTime=FALSE)

rawData <- rawData[,c("agency_cd","site_no","datetime","X15_00060_00003","X15_00060_00003_cd")] 

if(nrow(rawData)>0){
  names(rawData) <- c('agency', 'site', 'dateTime', 'value', 'code')
  rawData$dateTime <- as.Date(rawData$dateTime)
}

Daily <- populateDaily(rawData,35.314667)
```

Let me know if that's not what you are asking.
