### ISSUE TITLE
fluxUnit for bacteria

### ISSUE THREAD

**Issue by echriste1950** [USGS-R/EGRET#90]
There does not appear to be any defined fluxUnit for bacteria (concentration units = colonies/100mL). Any suggestions for a work around? or have I just missed something?

**Comment by ldecicco-USGS** [comment]
Yeah, it's not well documented...I should work on that.

You need to create a "fluxUnit" object. Here's some code that works, but you'll need to update the conversion value:

```
library(EGRET)
newFlux <- new("fluxUnit", shortName = "colonies/100mL",
              unitFactor = 1,
              unitName = "colonies/100mL",
              unitExpress = expression("Flux in colonies / 100 ml"),
              unitExpressTiny = expression("Flux (colonies/100 ml)"),
              unitUSGS = "colonies per 100 milliliter",
              shortCode = 14)

eList <- Choptank_eList

plotFluxQ(eList, fluxUnit = newFlux)
```


![2016-07-14_15-47-48](https://cloud.githubusercontent.com/assets/1105215/16855393/c73ba820-49da-11e6-8c6f-65b7f8e8fb35.png)

**Comment by echriste1950** [comment]
I think I see how this might work, but I am still very much in the copy and paste commands phase on the learning curve. So if my data is - bacteria concentration in colonies/100mL and flow in ft3/s - how can I specify some meaningful fluxUnit for instance million colonies/day like The output from rloadest. It looks like unitFactor might be the key?

**Comment by ldecicco-USGS** [comment]
A unitFactor of 1 is for flux of kg/day, and that's based on concentration data being in mg/L and flow being m^3/s. 

So...the concentration is multiplied by flow and unitFactor and 86.4:

```r
flux <- 86.4*unitFactor*Flow*Concentration
```

If you are like me, you'll need to get out some paper and work out your unitFactor. 

I calculate this...but DOUBLE CHECK:

```r
col   | ft^3|   60 s  | 60 min | 24 hr | 3.53147e-5 ml | 
--------------------------------------------------------------- 
100 ml |  s  | min  |  hr       | day    |    ft^3               |

0.03061279 / 86.4
0.03543147 / 10^6

3.543147e-08
```

Now....if you put in your flow data via `readNWISDaily`...the flow was converted from ft^3/s to cms....so then I guess it would be 1e-5

But...don't trust my conversions straight away.

**Comment by echriste1950** [comment]
I did pull the flow data with readNWISDaily. I will sharpen my pencil and
check the conversion.

I think there may be enough people ou there working with bacteria loads
because of TMDLs that a fluxUnit for bacteria might be warranted.

Thanks for the help.

Eric D Christensen
USGS-Missouri WSC
401 NW Capital Drive
Lee's Summit. MO 64086
Phone: 816.554.3489 Ext. 204
FAX: 816.554.9273

**Comment by ldecicco-USGS** [comment]
If you confirm the conversion...I'll add it to the package.

**Comment by echriste1950** [comment]
*colonies* x *m3* x *1000000 mL * x *86400 s* = *864000000 colonies* / *
  1      * = *864 million colonies*
100mL       s              m3                 d                         d
               1000000                d

 Assuming the formula:
   Flux <- 86.4*unitFactor*Flow*Concentration
Then the unitFactor would be:
   864 / 86.4 -- unitFactor = 10 for million colonies per day
   864000000 / 86.4 -- unitFactor = 10000000 for colonies per day

I think million coloniees per day would be the preferred unit.

Eric D Christensen
USGS-Missouri WSC
401 NW Capital Drive
Lee's Summit. MO 64086
Phone: 816.554.3489 Ext. 204
FAX: 816.554.9273

**Comment by echriste1950** [comment]
Well the conversion formula got pretty scrambled on the USGS-R/EGRET page (I now see the point of your formatting). Looks OK in the email version - let me know if you want me to redo.

**Comment by ldecicco-USGS** [comment]
OK, you've made me fill a whiteboard up with scratching....
I'm revising my statement...I think the number you want is 10.

A unit factor of 1 changes mg/L to kg/day in basic EGRET. All concentration measurements are assumed to be in mg/L...

So, if we go from colonies to "millions of colonies"...that's the same as mg -> kg
Then, the only difference between col/100ml and mg/L is a factor of 10. 

It took me and a co-worker a long time to agree that that factor of 10 is the unit factor (not 0.1....)

Does that sound right? I could try to format an equation, but maybe those words makes sense..

**Comment by ldecicco-USGS** [comment]
Either way, I'll be on vacation next week. If you want to make some `EGRET` plots in the meantime, I think you'll want to do this:
```
library(EGRET)
newFlux <- new("fluxUnit", shortName = "Mcol/day",
              unitFactor = 10,
              unitName = "Mcol/day",
              unitExpress = expression("Flux in millions of colonies / day"),
              unitExpressTiny = expression("Flux (Mcol/day)"),
              unitUSGS = "Millions of colonies per day",
              shortCode = 14)
plotFluxQ(eList, fluxUnit = newFlux)
```
So, any `EGRET` function that has flux, you can input the `newFlux`.

**Comment by echriste1950** [comment]
Thanks. I too had a couple coworkers check the calculation so I feel pretty
good about it.

Sent from my iPhone

On Jul 15, 2016, at 4:26 PM, Laura DeCicco <notifications@github.com> wrote:

Either way, I'll be on vacation next week. If you want to make some EGRET
plots in the meantime, I think you'll want to do this:

library(EGRET)
newFlux <- new("fluxUnit", shortName = "Mcol/day",
              unitFactor = 10,
              unitName = "Mcol/day",
              unitExpress = expression("Flux in millions of colonies / day"),
              unitExpressTiny = expression("Flux (Mcol/day)"),
              unitUSGS = "Millions of colonies per day",
              shortCode = 14)
plotFluxQ(eList, fluxUnit = newFlux)

So, any EGRET function that has flux, you can input the newFlux.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/USGS-R/EGRET/issues/90#issuecomment-233073855>, or mute
the thread

**Comment by ldecicco-USGS** [comment]
We can ask @rmhirsch49 ...but I'm changing my mind on adding it to the package. Since this conversion would assume the concentration is in `col/100ml`...that goes against A LOT of documentation that specifies the concentration must be in `mg/L`. 

Now that you have the code above though, it should be pretty trivial to use the custom `newFlux` in your code. 

Also...before I erase my whiteboard...what did you and your co-workers agree on the unitFactor? 10 or 10,000,000?

**Comment by rmhirsch49** [comment]
Laura: I think this is a great example of something we can put on the blog.  We can walk people through the way to make a bacteria example work out without us needing to change the code.

Bob

**Comment by echriste1950** [comment]
Laura,

I see your point and agree with Bob that the more things get documented on
the blog or elsewhere the better. I personally have found the vignettes
helpful, but probably not enough here to do one on dealing with bacteria.

unitFactor=10 - not so many zeroes to count.

Eric D Christensen
USGS-Missouri WSC
401 NW Capital Drive
Lee's Summit. MO 64086
Phone: 816.554.3489 Ext. 204
FAX: 816.554.9273

**Comment by echriste1950** [comment]
Eric Christensen has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=187102321219-1cb4b2gdr0bqv5u5n35vi1hecjcp1sjg.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.download%2Fg.php&customparam=customparam>
