### ISSUE TITLE
https changeover

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/EGRET#96]
Found these lines with http .gov URLs using https://github.com/wdwatkins/gran_http_gov

HTTPS is supposed be available for everything by the end of December, but may not be yet.

Some of these in .md and other documentation files won't show up on github unless you go to raw file. Line numbers reference the number in the raw file when opened in a text editor, so the link may not point you to the right spot in some cases if lines are wrapping, etc.

- [x] https://github.com/USGS-R/EGRET/blob/master/DESCRIPTION#L22
- [x] https://github.com/USGS-R/EGRET/blob/master/DESCRIPTION#L29
- [ ] https://github.com/USGS-R/EGRET/blob/master/LICENSE.note#L1
- [x] https://github.com/USGS-R/EGRET/blob/master/R/EGRET.R#L11
- [x] https://github.com/USGS-R/EGRET/blob/master/R/readNWISDaily.r#L3
- [x] https://github.com/USGS-R/EGRET/blob/master/R/readNWISDaily.r#L4
- [x] https://github.com/USGS-R/EGRET/blob/master/R/readNWISDaily.r#L5
- [x] https://github.com/USGS-R/EGRET/blob/master/R/readNWISSample.r#L3
- [x] https://github.com/USGS-R/EGRET/blob/master/R/readNWISSample.r#L4
- [x] https://github.com/USGS-R/EGRET/blob/master/README.md#L12
- [x] https://github.com/USGS-R/EGRET/blob/master/README.md#L38
- [x] https://github.com/USGS-R/EGRET/blob/master/README.md#L233
- [ ] https://github.com/USGS-R/EGRET/blob/master/inst/CITATION#L14
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L566
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L994
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L996
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L2001
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L2014
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/EGRET.Rnw#L2017
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/rResid.html#L140
- [x] https://github.com/USGS-R/EGRET/blob/master/inst/doc/rResid.Rmd#L123
- [x] https://github.com/USGS-R/EGRET/blob/master/man/EGRET-package.Rd#L16
- [x] https://github.com/USGS-R/EGRET/blob/master/man/readNWISDaily.Rd#L44
- [x] https://github.com/USGS-R/EGRET/blob/master/man/readNWISDaily.Rd#L45
- [x] https://github.com/USGS-R/EGRET/blob/master/man/readNWISDaily.Rd#L46
- [x] https://github.com/USGS-R/EGRET/blob/master/man/readNWISSample.Rd#L40
- [x] https://github.com/USGS-R/EGRET/blob/master/man/readNWISSample.Rd#L41
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L566
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L994
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L996
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L2001
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L2014
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/EGRET.Rnw#L2017
- [x] https://github.com/USGS-R/EGRET/blob/master/vignettes/rResid.Rmd#L123

**Comment by ldecicco-USGS** [comment]
so missed license and citation when I did this awhile back.

**Comment by ldecicco-USGS** [comment]
@lindsaycarr can you take this issue on with your testing work?

**Comment by lindsaycarr** [comment]
lol you finished this before I could even read what it said to do :+1:
