### ISSUE TITLE
as.qw freezes machine

### ISSUE THREAD

**Issue by akbaldwi-usgs** [USGS-R/EGRET#97]
I'm trying to convert some censored data into the qw object type so that rloadest handles it correctly. (I can't pull the data from NWIS). I've tried the code below but it repeatedly freezes my computer. I'm wondering if anyone has suggestions on what I'm doing wrong. 
Thanks in advance- 
Austin Baldwin

 (careful- running this may freeze your machine!)

```
library(smwrQW)

conc <- c(0.07, 0.04, 0.025, 0.025)
rk <- c("", "", "<", "<")
rl <- c(0.025, 0.025, 0.025, 0.025)

DF <- data.frame(conc, rk, rl)

DF$rk <- as.character(DF$rk)

DF$qwconc <- as.qw(values=DF$conc, remark.codes=DF$rk, value.codes="",
               reporting.level=DF$rl, reporting.units = "none", analyte.method = "none",
               analyte.name = "none", unique.code = "none", value2="none")
```

**Comment by ldecicco-USGS** [comment]
I think you want to move this to:

https://github.com/USGS-R/smwrQW/issues

**Comment by akbaldwi-usgs** [comment]
Oh, right. Sorry, Laura!

*Austin Baldwin | *USGS Idaho Water Science Center | 230 Collins Rd, Boise,
ID  83702 |
office:(208) 387-1365  cell:(208) 912-9021 | akbaldwi@usgs.gov

**Comment by ldecicco-USGS** [comment]
(I'm having a look now.)
