### ISSUE TITLE
readNWISDaily: Values not numeric

### ISSUE THREAD

**Issue by hdugan** [USGS-R/EGRET#98]
Hi, 
Trying to download data using readNWISDaily. Running into the error
`Error in rawData$value/qConvert : non-numeric argument to binary operator`
This is because the data grabbed using dataRetrieval::importRDB1 has the values stored as characters. I think a simple as.numeric() would fix this issue. But there might be a better way. 

Example:
```
readNWISDaily('05427850','00060')
Error in rawData$value/qConvert : non-numeric argument to binary operator

```

**Comment by ldecicco-USGS** [comment]
Interesting. There's a field:
```
"***  Temporarily unavailable"
```
In the data. Usually there's a "no value" field that would automatically convert it to NA. Anyway, I can put a fix in there...I'll let you know when it's ready....But if you want something to work right now, you could do:

```
library(dataRetrieval)
url <- constructNWISURL('05427850','00060','','',"dv",statCd="00003", format = "tsv")
data <- importRDB1(url, asDateTime=FALSE)
data$X154921_00060_00003 <- as.numeric(data$X154921_00060_00003)

names(data) <- c('agency', 'site', 'dateTime', 'value', 'code')
data$dateTime <- as.Date(data$dateTime) 
Daily <- populateDaily(data,35.314667)
```

Be aware there are some negative flows in there. `EGRET`'s not going to be too happy about those.

**Comment by hdugan** [comment]
Cool, no rush. I just dug into the function, and did pretty much the same fix. 

I'll be careful about the negative flows, and the missing values. So far EGRET is great!
